#let data = yaml("data/cv-data.yaml")

#set page(
  paper: "a4",
  margin: (x: 1.5cm, y: 1.5cm),
  numbering: "1",
  header: align(right)[
    #set text(size: 8pt, fill: rgb("#666666"))
    Version: #datetime.today().display("[year]-[month]-[day]")
  ]
)

#set text(
  size: 9pt,
  lang: "en",
)

#set par(justify: true)

#let primary-color = rgb("#1a73e8")
#let text-color = rgb("#333333")
#let gray-color = rgb("#666666")
#let link-color = rgb("#0056b3")
#let sidebar-color = rgb("#fafafa")

#show link: set text(fill: link-color)

#show heading.where(level: 1): it => [
  #set text(fill: primary-color, size: 1.8em)
  #it
  #line(length: 100%, stroke: 1pt + primary-color)
  #v(0.3em)
]

#show heading.where(level: 2): it => [
  #set text(fill: text-color, size: 1.1em)
  #it
  #v(0.3em)
]

#grid(
  columns: (30%, 70%),
  gutter: 2em,
  
  // Sidebar
  block(
    fill: sidebar-color,
    inset: 1.5em,
    radius: 8pt,
    width: 100%,
    [
    #if data.basics.photo != none {
      let photo-path = data.basics.photo
      if photo-path.starts-with("/") {
        photo-path = photo-path.slice(1)
      }
      block(radius: 50%, clip: true, image(photo-path, width: 100%))
    }
    
    #v(0.5em)
    
    = Contact
    
    #let icon(name) = {
      if name == "location" { "📍" }
      else if name == "email" { "📧" }
      else if name == "phone" { "📱" }
      else if name == "website" { "🌐" }
      else if name == "birthdate" { "🎂" }
      else if name == "nationality" { "🌍" }
    }
    
    #grid(
      columns: (auto, 1fr),
      row-gutter: 0.8em,
      column-gutter: 0.5em,
      align: horizon,
      icon("location"), [#data.basics.location],
      icon("email"), [
        #if type(data.basics.email) == array {
          for e in data.basics.email [
            #link("mailto:" + e)[#e] \
          ]
        } else {
          link("mailto:" + data.basics.email)[#data.basics.email]
        }
      ],
      icon("phone"), [
        #if "phoneUrl" in data.basics [
          #link(data.basics.phoneUrl)[#data.basics.phone]
        ] else [
          #data.basics.phone
        ]
      ],
      icon("website"), [#link("https://" + data.basics.website)[#data.basics.website]]
    )
    
    #v(0.5em)
    
    = Personal
    #grid(
      columns: (auto, 1fr),
      row-gutter: 0.8em,
      column-gutter: 0.5em,
      align: horizon,
      icon("birthdate"), [#data.basics.birthdate],
      icon("nationality"), [#data.basics.nationality]
    )
    #v(0.5em)
    
    = Languages
    #for lang in data.languages [
      #v(0.2em)
      *#lang.language* \
      #if "fluency" in lang [
        #text(style: "italic", size: 0.9em)[#lang.fluency] \
      ]
      #if "skills" in lang [
        #set text(size: 0.8em)
        #grid(
          columns: (auto, auto),
          gutter: 0.5em,
          [Listening:], [#lang.skills.listening],
          [Reading:], [#lang.skills.reading],
          [Writing:], [#lang.skills.writing],
          [Spoken Prod.:], [#lang.skills.spokenProduction],
          [Spoken Int.:], [#lang.skills.spokenInteraction],
        )
      ]
      #v(0.5em)
    ]

    #if "latestVersionUrl" in data.basics [
       #v(1fr)
       #block(breakable: false, width: 100%)[
         // QR code is generated by src/generate-qr.ts before compilation
         #align(center)[
           #block(width: 3cm, radius: 8pt, fill: rgb("#FFFFFF"), inset: 4pt, image("images/qr-code.png", width: 100%))
           #link(data.basics.latestVersionUrl)[Latest Version] \
           #text(size: 0.8em)[#data.basics.latestVersionUrl.replace("https://", "")]
         ]
       ]
    ]
  ]),
  
  // Main Content
  [
    = #data.basics.name
    
    #text(style: "italic", fill: gray-color)[#data.basics.tagline]
    
    #v(0.8em)
    
    #if data.basics.summary != none [
      #data.basics.summary
    ]
    
    = Work Experience
    #for w in data.work [
      #grid(
        columns: (1fr, auto),
        align(left)[== #w.position],
        align(right)[#text(fill: gray-color)[#w.startDate - #w.endDate]]
      )
      #text(style: "italic")[#w.company, #w.location] \
      #if "description" in w [
        #w.description
      ]
      #v(0.8em)
    ]
    
    = Education
    #for edu in data.education [
      #grid(
        columns: (1fr, auto),
        align(left)[== #edu.degree],
        align(right)[#text(fill: gray-color)[#edu.startDate - #edu.endDate]]
      )
      #text(style: "italic")[
        #if "website" in edu [
          #link(edu.website)[#edu.institution]
        ] else [
          #edu.institution
        ], #edu.location
      ] \
      #if "level" in edu [
        #edu.level
      ]
      #v(0.8em)
    ]

    #if data.deployments != none [
      = Deployments
      #for dep in data.deployments [
        #grid(
          columns: (1fr, auto),
          align(left)[== #dep.position],
          align(right)[#text(fill: gray-color)[#dep.startDate - #dep.endDate]]
        )
        #text(style: "italic")[#dep.organization, #dep.location] \
        #dep.description
        #v(0.8em)
      ]
    ]
    
    #if data.trainings != none [
      = Trainings
      #for train in data.trainings [
        - *#train.event* (#train.year)
      ]
      #v(0.8em)
    ]
  ]
)
