#let data = yaml("/public/data/cv-data.yaml")

#set page(
  paper: "a4",
  margin: (x: 1.5cm, y: 1.5cm),
  numbering: "1",
  header: align(right)[
    #set text(size: 8pt, fill: rgb("#666666"))
    Version: #datetime.today().display("[year]-[month]-[day]")
  ]
)

#set text(
  size: 9pt,
  lang: "en",
  font: "Roboto",
)

#set par(justify: true)

#let primary-color = rgb("#1a73e8")
#let text-color = rgb("#333333")
#let gray-color = rgb("#666666")
#let link-color = rgb("#0056b3")
#let sidebar-color = rgb("#fafafa")

#show link: set text(fill: link-color)

#show heading.where(level: 1): it => [
  #set text(fill: primary-color, size: 1.4em)
  #it
  #v(-0.3em)
  #line(length: 100%, stroke: 1pt + primary-color)
  #v(0.2em)
]

#show heading.where(level: 2): it => [
  #set text(fill: text-color, size: 1em)
  #it
  // #v(0.1em)
]

#grid(
  columns: (30%, 1fr),
  gutter: 2em,
  
  // Sidebar
  block(
    fill: sidebar-color,
    inset: 1.5em,
    radius: 8pt,
    width: 100%,
    [
    #set par(justify: false)
    #if data.basics.photo != none {
      let photo-path = data.basics.photo
      if photo-path.starts-with("/") {
        photo-path = "/public" + photo-path
      }
      block(radius: 50%, clip: true, image(photo-path, width: 100%))
    }
    
    #v(0.3em)
    
    = Contact
    
    #let icon(name) = {
      if name == "location" { "📍" }
      else if name == "email" { "📧" }
      else if name == "phone" { "📱" }
      else if name == "website" { "🌐" }
      else if name == "linkedin" { "🔗" }
      else if name == "birthdate" { "🎂" }
      else if name == "nationality" { "🌍" }
    }
    
    #grid(
      columns: (auto, 1fr),
      row-gutter: 0.8em,
      column-gutter: 0.5em,
      align: horizon,
      icon("location"), [#data.basics.location],
      icon("email"), [
        #if type(data.basics.email) == array {
          for e in data.basics.email [
            #link("mailto:" + e)[#e] \
          ]
        } else {
          link("mailto:" + data.basics.email)[#data.basics.email]
        }
      ],
      icon("phone"), [
        #if "phoneUrl" in data.basics [
          #link(data.basics.phoneUrl)[#data.basics.phone]
        ] else [
          #data.basics.phone
        ]
      ],
      icon("website"), [#link("https://" + data.basics.website)[#data.basics.website]]
    )
    
    #v(0.3em)
    
    #if "linkedin" in data.basics [
      #grid(
        columns: (auto),
        gutter: 1em,
        link("https://" + data.basics.linkedin)[
          #image("/public/images/linkedin.svg", width: 1.5em)
        ]
      )
    ]
    
    #v(0.3em)
    
    = Personal
    #grid(
      columns: (auto, 1fr),
      row-gutter: 0.8em,
      column-gutter: 0.5em,
      align: horizon,
      icon("birthdate"), [#data.basics.birthdate],
      icon("nationality"), [#data.basics.nationality]
    )
    #v(0.3em)
    
    = Languages
    #for lang in data.languages [
      #v(0.2em)
      *#lang.language* \
      #if "fluency" in lang [
        #text(style: "italic", size: 0.9em)[#lang.fluency] \
      ]
      #if "skills" in lang [
        #set text(size: 0.8em)
        #grid(
          columns: (auto, auto),
          gutter: 0.5em,
          [Listening:], [#lang.skills.listening],
          [Reading:], [#lang.skills.reading],
          [Writing:], [#lang.skills.writing],
          [Spoken Prod.:], [#lang.skills.spokenProduction],
          [Spoken Int.:], [#lang.skills.spokenInteraction],
        )
      ]
      #v(0.5em)
    ]

    #if "latestVersionUrl" in data.basics [
       #v(1fr)
       #block(breakable: false, width: 100%)[
         // QR code is generated by src/generate-qr.ts before compilation
         #align(center)[
           #block(width: 3cm, radius: 8pt, fill: rgb("#FFFFFF"), inset: 4pt, image("/public/images/qr-code.png", width: 100%))
           #link(data.basics.latestVersionUrl)[Latest CV] \
           #text(size: 0.8em)[#data.basics.latestVersionUrl.replace("https://", "")]
         ]
       ]
    ]
  ]),
  
  // Main Content
  [
    = #data.basics.name
    
    #text(style: "italic", fill: gray-color)[#data.basics.tagline]
    
    #v(0.8em)
    
    #if data.basics.summary != none [
      #data.basics.summary
    ]
    
    #for (key, title) in data.sections {
      if key == "work" {
        [
          = #title
          #for w in data.work [
            #grid(
              columns: (1fr, auto),
              align(left)[== #w.position],
              align(right)[#text(fill: gray-color)[#w.startDate - #w.endDate]]
            )
            #text(style: "italic")[#w.company#if "location" in w [, #text(fill: gray-color)[#w.location]]] \
            #if "description" in w [
              #w.description
            ]
            #v(0.5em)
          ]
        ]
      } else if key == "education" {
        [
          = #title
          #for edu in data.education [
            #grid(
              columns: (1fr, auto),
              align(left)[== #edu.degree],
              align(right)[#text(fill: gray-color)[#edu.startDate - #edu.endDate]]
            )
            #text(style: "italic")[
              #if "website" in edu [
                #link(edu.website)[#edu.institution]
              ] else [
                #edu.institution
              ]#if "location" in edu [, #text(fill: gray-color)[#edu.location]]
            ] \
            #if "level" in edu [
              #edu.level
            ]
            #if "description" in edu [
              \ #edu.description
            ]
            #v(0.5em)
          ]
        ]
      } else if key == "volunteering" {
        if data.volunteering != none {
          [
            = #title
            #for vol in data.volunteering [
              #grid(
                columns: (1fr, auto),
                align(left)[== #vol.position],
                align(right)[#text(fill: gray-color)[#vol.startDate - #vol.endDate]]
              )
              #text(style: "italic")[#vol.organization] \
              #if "summary" in vol [
                #vol.summary
              ]
              #v(0.5em)
            ]
          ]
        }
      } else if key == "deployments" {
        if data.deployments != none {
          [
            = #title
            #for dep in data.deployments [
              #grid(
                columns: (1fr, auto),
                align(left)[== #dep.position],
                align(right)[#text(fill: gray-color)[#dep.startDate - #dep.endDate]]
              )
              #text(style: "italic")[#dep.organization#if "location" in dep [, #text(fill: gray-color)[#dep.location]]] \
              #dep.description
              #v(0.5em)
            ]
          ]
        }
      } else if key == "trainings" {
        if data.trainings != none {
          [
            = #title
            #let current-year = ""
            #for train in data.trainings {
              if train.year != current-year {
                current-year = train.year
                v(0.8em)
                text(weight: "bold", size: 1em, fill: primary-color)[#current-year]
                v(-0.3em)
                line(length: 100%, stroke: 0.5pt + rgb("#eeeeee"))
                v(0.3em)
              }
              grid(
                columns: (1em, 1fr),
                gutter: 0.5em,
                align(top + right)[•],
                align(left)[
                  *#train.organization*#if "location" in train [, #text(style: "italic", fill: gray-color)[#train.location]] \
                  #train.course #if "language" in train [ #sym.bullet #text(style: "italic", fill: gray-color)[#train.language] ]
                ]
              )
              v(0.4em)
            }
            #v(0.5em)
          ]
        }
      }
    }
  ]
)
